# Generated by Django 5.2.3 on 2025-06-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passwd', models.CharField(max_length=8)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
